# Steps in data cleaning :
1. Inspection(already done in data understanding file).
2. Remove duplicates.
3. Handle missing values
4. Correct data types
5. Standardize text data.
6. Fix inconsistent categories like 'delhi' and 'Delhi'.
7. Handle invalid values.
8. Detect and handle outliers.
9. Remove unnecessary columns.

In [ ]:
import numpy as np
import pandas as pd
from google.colab import files

# Cleaning the Customer Flight Activity dataset

In [ ]:
activity = pd.read_csv('/content/Customer Flight Activity.csv')
activity.head(3)

,Loyalty Number,Year,Month,Total Flights,Distance,Points Accumulated,Points Redeemed,Dollar Cost Points Redeemed
0,100590,2018,6,12,15276,22914.0,0,0
1,100590,2018,7,12,9168,13752.0,0,0
2,100590,2018,5,4,6504,9756.0,0,0

# 1. Missing Values

In [ ]:
activity.info()
# no missing values.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 392936 entries, 0 to 392935
Data columns (total 8 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   Loyalty Number               392936 non-null  int64
 1   Year                         392936 non-null  int64
 2   Month                        392936 non-null  int64
 3   Total Flights                392936 non-null  int64
 4   Distance                     392936 non-null  int64
 5   Points Accumulated           392936 non-null  float64
 6   Points Redeemed              392936 non-null  int64
 7   Dollar Cost Points Redeemed  392936 non-null  int64
dtypes: float64(1), int64(7)
memory usage: 24.0 MB

# 2. Remove Duplicates

In [ ]:
activity = activity.drop_duplicates()
activity.duplicated().sum()

np.int64(0)

# 3. Correct datatypes

In [ ]:
activity.info()
# no incorrect data types

<class 'pandas.core.frame.DataFrame'>
Index: 391014 entries, 0 to 392935
Data columns (total 8 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   Loyalty Number               391014 non-null  int64
 1   Year                         391014 non-null  int64
 2   Month                        391014 non-null  int64
 3   Total Flights                391014 non-null  int64
 4   Distance                     391014 non-null  int64
 5   Points Accumulated           391014 non-null  float64
 6   Points Redeemed              391014 non-null  int64
 7   Dollar Cost Points Redeemed  391014 non-null  int64
dtypes: float64(1), int64(7)
memory usage: 26.8 MB

# 4. Handle invalid values

In [ ]:
print((activity['Distance'] < 0).sum())
print((activity['Total Flights'] < 0).sum())
# No invalid values

0
0

# 5. Remove Unnecessary Columns
  'Dollar Cost Points Redeemed' column is unnecessary
  and therefore we will remove it.

In [ ]:
activity = activity.drop(columns = "Dollar Cost Points Redeemed")
activity.head(3)

,Loyalty Number,Year,Month,Total Flights,Distance,Points Accumulated,Points Redeemed
0,100590,2018,6,12,15276,22914.0,0
1,100590,2018,7,12,9168,13752.0,0
2,100590,2018,5,4,6504,9756.0,0

# 6. Outlier detection for numerical columns

In [ ]:
numeric_cols = activity[['Total Flights', 'Distance', 'Points Accumulated', 'Points Redeemed']]
outlier_summary = []
for col in numeric_cols :
  Q1 = activity[col].quantile(0.25)
  Q3 = activity[col].quantile(0.75)
  IQR = Q3 - Q1
  lower = Q1 - 1.5 * IQR
  upper = Q3 + 1.5 * IQR
  outliers = ((activity[col] < lower) | (activity[col] > upper)).sum()
  outlier_summary.append({
      'Column' : col,
      'lower_bound' : lower,
      'upper_bound' : upper,
      'outliers' : outliers,
      'percentage' : round(outliers * 100 / len(activity), 2)
  })
outlier_summary = pd.DataFrame(outlier_summary)
outlier_summary

               Column  lower_bound  upper_bound  outliers  percentage
0       Total Flights         -3.0          5.0      8911        2.28
1            Distance      -4560.0       7600.0     21595        5.52
2  Points Accumulated      -4590.0       7650.0     22053        5.64
3     Points Redeemed          0.0          0.0     23885        6.11

# 7. Handling outlier
Outliers were identified using the Interquartile Range (IQR) method. Although several numerical variables contained observations outside the IQR bounds, these values correspond to legitimate high-value customers (e.g., frequent flyers with high travel distances and loyalty point balances). Since these represent meaningful business behavior rather than data errors, no outliers were removed.

# 8. Saving the cleaned File

In [ ]:
activity.to_csv('customer_flight_activity_cleaned.csv', index = False)
files.download('customer_flight_activity_cleaned.csv')

# Cleaning the Customer Loyalty History dataset

In [ ]:
loyalty = pd.read_csv('/content/Customer Loyalty History.csv')
loyalty.head(3)

,Loyalty Number,Country,Province,City,Postal Code,Gender,Education,Salary,Marital Status,Loyalty Card,CLV,Enrollment Type,Enrollment Year,Enrollment Month,Cancellation Year,Cancellation Month
0,480934,Canada,Ontario,Toronto,M2Z 4K1,Female,Bachelor,83236.0,Married,Star,3839.14,Standard,2016,2,NaN,NaN
1,549612,Canada,Alberta,Edmonton,T3G 6Y6,Male,College,NaN,Divorced,Star,3839.61,Standard,2016,3,NaN,NaN
2,429460,Canada,British Columbia,Vancouver,V6E 3D9,Male,College,NaN,Single,Star,3839.75,Standard,2014,7,2018.0,1.0

# 1. Remove Duplicates

In [ ]:
loyalty = loyalty.drop_duplicates()
loyalty.duplicated().sum()

np.int64(0)

# 2. Handling missing values

In [ ]:
loyalty.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16737 entries, 0 to 16736
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Loyalty Number      16737 non-null  int64
 1   Country             16737 non-null  object
 2   Province            16737 non-null  object
 3   City                16737 non-null  object
 4   Postal Code         16737 non-null  object
 5   Gender              16737 non-null  object
 6   Education           16737 non-null  object
 7   Salary              12499 non-null  float64
 8   Marital Status      16737 non-null  object
 9   Loyalty Card        16737 non-null  object
 10  CLV                 16737 non-null  float64
 11  Enrollment Type     16737 non-null  object
 12  Enrollment Year     16737 non-null  int64
 13  Enrollment Month    16737 non-null  int64
 14  Cancellation Year   2067 non-null   float64
 15  Cancellation Month  2067 non-null   float64
dtypes: float64(4), int64(3), object(9)
memory usage: 2.0+ MB

In [ ]:
loyalty.groupby('Gender')['Salary'].apply(lambda x: x.isna().sum())

Gender
Female    2084
Male      2154
Name: Salary, dtype: int64

In [ ]:
loyalty.groupby('Education')['Salary'].apply(lambda x: x.isna().sum())

Education
bachelor                0
college                 0
doctor                  0
high school or below    0
master                  0
Name: Salary, dtype: int64

In [ ]:
loyalty.groupby('Education')['Salary'].apply(lambda x: x.isna().mean() * 100)

Education
Bachelor                  0.0
College                 100.0
Doctor                    0.0
High School or Below      0.0
Master                    0.0
Name: Salary, dtype: float64

In [ ]:
loyalty['Salary'] = loyalty['Salary'].fillna(loyalty['Salary'].median())
loyalty['Cancellation Year'] = loyalty['Cancellation Year'].fillna(0)
loyalty['Cancellation Month'] = loyalty['Cancellation Month'].fillna(0)
loyalty.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16737 entries, 0 to 16736
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Loyalty Number      16737 non-null  int64
 1   Country             16737 non-null  object
 2   Province            16737 non-null  object
 3   City                16737 non-null  object
 4   Postal Code         16737 non-null  object
 5   Gender              16737 non-null  object
 6   Education           16737 non-null  object
 7   Salary              16737 non-null  float64
 8   Marital Status      16737 non-null  object
 9   Loyalty Card        16737 non-null  object
 10  CLV                 16737 non-null  float64
 11  Enrollment Type     16737 non-null  object
 12  Enrollment Year     16737 non-null  int64
 13  Enrollment Month    16737 non-null  int64
 14  Cancellation Year   16737 non-null  float64
 15  Cancellation Month  16737 non-null  float64
dtypes: float64(4), int64(3), object(9)
memory usage: 2.0+ MB

There 4238 missing values in the Salary and interestingly all of them belonged to the same education grouop 'College'. This looks like a data collection issue. The missing values were replaced with the median of the whole salary column.
Naturally, there were missing values in the Cancellation Year and Cancellation Month columns which were replaced by 0.

# 3. Standardize Text Data

In [ ]:
text_cols = loyalty.select_dtypes(include = 'object').columns
loyalty[text_cols] = loyalty[text_cols].apply(lambda x : x.str.strip())
loyalty[text_cols] = loyalty[text_cols].apply(lambda x : x.str.lower())
loyalty[text_cols]

,Country,Province,City,Postal Code,Gender,Education,Marital Status,Loyalty Card,Enrollment Type
0,canada,ontario,toronto,m2z 4k1,female,bachelor,married,star,standard
1,canada,alberta,edmonton,t3g 6y6,male,college,divorced,star,standard
2,canada,british columbia,vancouver,v6e 3d9,male,college,single,star,standard
3,canada,ontario,toronto,p1w 1k4,male,college,single,star,standard
4,canada,quebec,hull,j8y 3z5,male,bachelor,married,star,standard
...,...,...,...,...,...,...,...,...,...
16732,canada,british columbia,vancouver,v6e 3z3,female,college,married,star,standard
16733,canada,saskatchewan,regina,s1j 3c5,female,bachelor,married,star,standard
16734,canada,british columbia,vancouver,v5r 1w3,male,college,single,star,standard
16735,canada,yukon,whitehorse,y2k 6r0,male,bachelor,married,star,2018 promotion
16736,canada,manitoba,winnipeg,r2c 0m5,female,bachelor,married,star,standard

# 4. Handling invalid values

In [ ]:
print((loyalty['Salary'] < 0).sum())
loyalty[loyalty['Salary'] < 0]

20

,Loyalty Number,Country,Province,City,Postal Code,Gender,Education,Salary,Marital Status,Loyalty Card,CLV,Enrollment Type,Enrollment Year,Enrollment Month,Cancellation Year,Cancellation Month
1082,542976,canada,quebec,montreal,h2y 4r4,male,high school or below,-49830.0,divorced,star,24127.50,2018 promotion,2018,3,0.0,0.0
1894,959977,canada,british columbia,vancouver,v5r 1w3,female,bachelor,-12497.0,married,aurora,9453.00,2018 promotion,2018,3,0.0,0.0
2471,232755,canada,british columbia,vancouver,v1e 4r6,female,bachelor,-46683.0,single,nova,4787.81,2018 promotion,2018,3,0.0,0.0
3575,525245,canada,british columbia,victoria,v10 6t5,male,bachelor,-45962.0,married,star,2402.33,2018 promotion,2018,3,0.0,0.0
3932,603070,canada,british columbia,west vancouver,v6v 8z3,female,bachelor,-19325.0,single,star,2893.74,2018 promotion,2018,3,0.0,0.0
4712,491242,canada,british columbia,dawson creek,u5i 4f1,male,bachelor,-43234.0,married,star,7597.91,2018 promotion,2018,3,0.0,0.0
6560,115505,canada,newfoundland,st. john's,a1c 6h9,male,bachelor,-10605.0,married,nova,5860.17,2018 promotion,2018,4,0.0,0.0
6570,430398,canada,newfoundland,st. john's,a1c 6h9,male,bachelor,-17534.0,married,nova,49423.80,2018 promotion,2018,3,0.0,0.0
7373,152016,canada,ontario,toronto,p1j 8t7,female,bachelor,-58486.0,married,aurora,5067.21,2018 promotion,2018,2,0.0,0.0
8576,194065,canada,ontario,sudbury,m5v 1g5,female,bachelor,-31911.0,married,nova,2888.85,2018 promotion,2018,2,0.0,0.0
8767,212128,canada,ontario,toronto,p2t 6g3,male,bachelor,-49001.0,married,nova,3130.68,2018 promotion,2018,2,0.0,0.0
10232,790475,canada,ontario,trenton,k8v 4b2,female,bachelor,-34079.0,married,nova,12913.50,2018 promotion,2018,2,0.0,0.0
11635,366599,canada,ontario,toronto,m1r 4k3,female,bachelor,-9081.0,married,star,6915.73,2018 promotion,2018,4,0.0,0.0
12596,436087,canada,quebec,montreal,h2t 9k8,male,bachelor,-46470.0,married,star,4786.89,2018 promotion,2018,4,2018.0,8.0
13564,364596,canada,quebec,tremblant,h5y 2s9,female,bachelor,-26322.0,single,aurora,16710.84,2018 promotion,2018,4,2018.0,12.0
14327,239955,canada,quebec,hull,j8y 3z5,female,bachelor,-47310.0,married,nova,6366.23,2018 promotion,2018,3,0.0,0.0
14355,347013,canada,quebec,quebec city,g1b 3l5,male,bachelor,-39503.0,married,nova,6446.71,2018 promotion,2018,3,0.0,0.0
15416,729561,canada,quebec,quebec city,g1b 3l5,female,bachelor,-19332.0,divorced,star,5308.29,2018 promotion,2018,2,0.0,0.0
16431,734647,canada,saskatchewan,regina,s1j 3c5,male,bachelor,-46303.0,married,nova,11280.73,2018 promotion,2018,4,0.0,0.0
16735,906428,canada,yukon,whitehorse,y2k 6r0,male,bachelor,-57297.0,married,star,10018.66,2018 promotion,2018,4,0.0,0.0

It's most likely a data entry error so we will replace them with the absolute value

In [ ]:
loyalty['Salary'] = abs(loyalty['Salary'])
print((loyalty['Salary'] < 0).sum())

0

# 5. Detecting Outliers

In [ ]:
numeric_cols = ['Salary', 'CLV']
loyalty[numeric_cols]
outlier_summary = []
for col in numeric_cols :
  Q1 = loyalty[col].quantile(0.25)
  Q3 = loyalty[col].quantile(0.75)
  IQR = Q3 - Q1
  lower = Q1 - 1.5 * IQR
  upper = Q3 + 1.5 * IQR
  outliers = ((loyalty[col] < lower) | (loyalty[col] > upper)).sum()
  outlier_summary.append({
      'Columns' : col,
      'lower_bound' : lower,
      'Upper_bound' : upper,
      'outliers' : outliers,
      'percentage' : round(outliers * 100 / len(loyalty), 2)
  })
outlier_summary = pd.DataFrame(outlier_summary)
outlier_summary

  Columns  lower_bound  Upper_bound  outliers  percentage
0  Salary     35337.50    111501.50       866        5.17
1     CLV     -3458.77     16380.19      1485        8.87

As before, The outliers are genuine data variations and therefore are kept intact.

# 6. Saving the File

In [ ]:
loyalty.to_csv('customer_loyalty_history.csv', index = False)
files.download('customer_loyalty_history.csv')